version: '3.7'

services:
  notes-server-db:
    image: 'postgres:14.2-alpine'
    container_name: notes-server-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes-server

  telegrambot-server-db:
    image: 'postgres:14.2-alpine'
    container_name: telegrambot-server-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=telegrambot-server

  rabbit-mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672